trigger: 
  - develop

pool: default

variables:
  CACHE_DIR: $(Pipeline.Workspace)/.cache
  SQLCL_DIR: $(Build.BinariesDirectory)/sqlcl
  UTPLSQL_DIR: $(Build.BinariesDirectory)/utPLSQL
  UTPLSQL_CLI_DIR: $(Build.BinariesDirectory)/utPLSQL-cli
  UTPLSQL_CLI_VERSION: 'v3.1.8'
  UTPLSQL_VERSION: 'v3.1.11' 
  DOCKHER_HUB_REPO: 'utplsqlv3/oracledb'
  DB_USER: test
  DB_PASS: test  

jobs:
- job: utPLSQL_demo_project
  displayName: Build utPLSQL-demo-project

  steps:

  - task: UseDotNet@2
    displayName: 'Use dotnet'

  - template: .azure_templates/t-task-extend-sqlcl.yml
    parameters:
      work_dir: $(Build.SourcesDirectory)
      user: $(DB_USER)
      password: $(DB_PASS)
      connectionString: localhost/xepdb1
      script: source/install.sql
      displayName: Install Source

  - template: .azure_templates/t-task-extend-sqlcl.yml
    parameters:
      work_dir: $(Build.SourcesDirectory)
      user: $(DB_USER)
      password: $(DB_PASS)
      connectionString: localhost/xepdb1
      script: test/install.sql
      displayName: Install Tests

  - template: .azure_templates/t-task-extend-utplsqlcli.yml
    parameters:
      work_dir: $(Build.SourcesDirectory)
      connectionString: localhost/xepdb1
      test_user: $(DB_USER)
      test_pwd: $(DB_PASS)
      source_path: source
      test_path: test
      options: --debug --failure-exit-code=0

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit_test_results.xml'
      testRunTitle: 'Publish test results'
    displayName: 'Publish test results'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'cobertura.xml'
      pathToSources: 'source'
    displayName: 'Publish coverage'
